apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 5
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      name: guestbook
      labels:
        app: guestbook
    spec:
      containers:
      - image: cellist01/cicd_guestbook:20230609175525_4
        name: sb-guestbook
        envFrom:
        - configMapRef:
            name: guestbook-cm
